name: Plugin2
main: com.eul4.plugin2.Main
version: 1.0
author: Eul4
api-version: '1.21'
depend: [ProtocolLib, Plugin]
commands:
  sethome:
    description: Define uma home
    usage: /sethome [nome]
  home:
    description: Vai para uma home definida
    usage: /home [nome]
  delhome:
  listhomes:
  tpa:
  aceitartpa: